# Generated by Django 4.1.3 on 2022-12-03 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("small_title", models.CharField(max_length=50)),
                (
                    "card_icon",
                    models.ImageField(
                        default="default/default.jpg", upload_to="post_images"
                    ),
                ),
                ("page_image", models.ImageField(upload_to="project_images")),
                ("slug", models.SlugField(unique=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("body", models.TextField()),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
