# Generated by Django 4.1.3 on 2022-11-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_posted"]},
        ),
    ]
