# Generated by Django 4.1.3 on 2022-11-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(
                default="default/default.jpg", upload_to="post_images"
            ),
        ),
    ]
