# Generated by Django 4.1.3 on 2022-12-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
    ]
